export { default as LoginPage } from './LoginPage/LoginPage'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as ProfilePage } from './ProfilePage/ProfilePage'
export { default as AddNewCollegeAdmin } from './CollegeAdmin/AddNewCollegeAdmin/AddNewCollegeAdmin'
export { default as ChangePassword } from './ChangePassword/ChangePassword'
export { default as STPListPage } from './STPListPage/STPListPage'